alias e=/opt/homebrew/lib/ruby/gems/3.3.0/bin/colorls
alias c=clear
alias tree="e --tree"
alias py=python3
alias zed="open -a /Applications/Zed.app -n"
alias ea="e -a"
alias eg= "e --git-status"
alias base="source ~/envs/base/bin/activate"
alias script="source ~/envs/langage_script/bin/activate"
alias ml="source ~/envs/ml/bin/activate"
alias game="source ~/envs/gamedev/bin/activate"
alias o="cd /Users/florianphilippe/Library/Mobile\ Documents/iCloud\~md\~obsidian/Documents/Vault/"
alias love="/Applications/love.app/Contents/MacOS/love"
alias books="cd /Users/florianphilippe/Library/Mobile\ Documents/iCloud\~com\~apple\~iBooks/Documents"
alias ubuntu="sh ~/.oh-my-zsh/custom/scripts/ubuntu.sh"
alias ubuntucp="docker cp ~/C fb784e328b17:/root"
